### ISSUE TITLE
Measurement Type Don't change

### ISSUE THREAD

**Issue by presian0** [tunasayin/speedometer#4]
![Screenshot_1](https://github.com/user-attachments/assets/4b7f998e-95af-45c0-9dd7-792917d2c232)

Its a good script i like it but cant change the data to show kph

**Comment by tunasayin** [comment]
You need to change the measurement type from the game settings. I believe it's bad pratice to enforce one measurement type to users by setting the measurement type in the script config.

**Comment by presian0** [comment]
actualy after looking up the code more is you just need to change the isMetric to isMetric = true
